clusterid: wrong
cloudregion: wrong
role: wrong

openshift_cluster_content:
- object: Cluster Autoscaling
  content:
  - name: ClusterAutoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
  - name: "MachineAutoscaler zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
    namespace: openshift-machine-api
  - name: "MachineAutoscaler zone {{ cloudregion }}b"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
    namespace: openshift-machine-api
  - name: "MachineAutoscaler zone {{ cloudregion }}c"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
    namespace: openshift-machine-api
- object: Htpasswd
  content:
    - name: Oauth
      template: "{{ inventory_dir }}/../templates/htprovider.yaml"
      params_from_vars:
        HTPASSWD_PROVIDER: my_htpasswd_provider
        HTPASSWD_SECRET: htpass-secret
- object: Custom Machinesets
  content:
  - name: "MachineAutoscaler zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml" 
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
      ROLE: "{{ role }}"
    namespace: openshift-machine-api
  - name: "MachineAutoscaler zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
      ROLE: "{{ role }}"
    namespace: openshift-machine-api
  - name: "MachineAutoscaler zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
      ROLE: "{{ role }}"
    namespace: openshift-machine-api


