clusterid: wrong
cloudregion: wrong
role: wrong
amiid: wrong
machinetype: wrong
securitygroup: wrong
iamprofile: wrong
min: wrong
max: wrong

openshift_cluster_content:
- object: Custom Machinesets
  content:
  - name: "MachineSet {{ role }} zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml" 
    params_from_vars:
      AMI_ID: "{{ amiid }}"
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
      ROLE: "{{ role }}"
      MACHINE_TYPE: "{{ machinetype }}"
      SECURITY_GROUP: "{{ securitygroup }}"
      IAM_PROFILE: "{{ iamprofile }}"
      PRIVATE_SUBNET: "{{ clusterid }}-private-{{ cloudregion }}a"
    namespace: openshift-machine-api
    tags:
    - machinesets
  - name: "MachineSet {{ role }} zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml"
    params_from_vars:
      AMI_ID: "{{ amiid }}"
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
      ROLE: "{{ role }}"
      MACHINE_TYPE: "{{ machinetype }}"
      SECURITY_GROUP: "{{ securitygroup }}"
      IAM_PROFILE: "{{ iamprofile }}"
      PRIVATE_SUBNET: "{{ clusterid }}-private-{{ cloudregion }}b"
    namespace: openshift-machine-api
    tags:
    - machinesets
  - name: "MachineSet {{ role }} zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineset.yaml"
    params_from_vars:
      AMI_ID: "{{ amiid }}"
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION: "{{ cloudregion }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
      ROLE: "{{ role }}"
      MACHINE_TYPE: "{{ machinetype }}"
      SECURITY_GROUP: "{{ securitygroup }}"
      IAM_PROFILE: "{{ iamprofile }}"
      PRIVATE_SUBNET: "{{ clusterid }}-private-{{ cloudregion }}c"
    namespace: openshift-machine-api
    tags:
    - machinesets
- object: Cluster Autoscaling
  content:
  - name: ClusterAutoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
    tags:
    - autoscaling
  - name: "MachineAutoscaler zone {{ cloudregion }}a"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
      ROLE: "{{ role }}"
      MIN: "{{ min }}"
      MAX: "{{ max }}"
    namespace: openshift-machine-api
    tags:
    - autoscaling
  - name: "MachineAutoscaler zone {{ cloudregion }}b"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
      ROLE: "{{ role }}"
      MIN: "{{ min }}"
      MAX: "{{ max }}"
    namespace: openshift-machine-api
    tags:
    - autoscaling
  - name: "MachineAutoscaler zone {{ cloudregion }}c"
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
      ROLE: "{{ role }}"
      MIN: "{{ min }}"
      MAX: "{{ max }}"
    namespace: openshift-machine-api
    tags:
    - autoscaling
- object: Htpasswd
  content:
  - name: Oauth
    template: "{{ inventory_dir }}/../templates/htprovider.yaml"
    params_from_vars:
      HTPASSWD_PROVIDER: my_htpasswd_provider
      HTPASSWD_SECRET: htpass-secret
    tags:
    - auth

