---
apiVersion: v1
kind: Template
objects:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata: 
    labels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID}
    name: ${CLUSTER_ID}-${ROLE}-${CLOUD_REGION_ZONE}
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID}
        machine.openshift.io/cluster-api-machineset: ${CLUSTER_ID}-${ROLE}-${CLOUD_REGION_ZONE}
    template:
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID}
          machine.openshift.io/cluster-api-machine-role: ${ROLE}
          machine.openshift.io/cluster-api-machine-type: ${ROLE}
          machine.openshift.io/cluster-api-machineset: ${CLUSTER_ID}-${ROLE}-${CLOUD_REGION_ZONE}
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/${ROLE}: ""
        providerSpec:
          value:
            ami:
              id: ${AMI_ID}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: ${IAM_PROFILE}
            instanceType: ${MACHINE_TYPE}
            kind: AWSMachineProviderConfig
            placement:
              availabilityZone: ${CLOUD_REGION_ZONE}
              region: ${CLOUD_REGION}
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - ${SECURITY_GROUP}
            subnet:
              filters:
              - name: tag:Name
                values:
                - ${PRIVATE_SUBNET}
            tags:
            - name: kubernetes.io/cluster/${CLUSTER_ID}
              value: owned
            userDataSecret:
              name: worker-user-data
parameters:
- name: AMI_ID
  description: "Grab the ami for your region"
  required: true
- name: CLUSTER_ID
  description: "Example Value - mycluster-dev-x85t8"
  required: true
- name: CLOUD_REGION
  description: "Region but no az. Example Value - us-east-1"
  required: true
- name: CLOUD_REGION_ZONE
  description: "Region & az. Example Value - us-east-1a"
  required: true
- name: ROLE
  description: "Role of Machineset creating. Example Value - worker"
  required: true
- name: MACHINE_TYPE
  description: "Machine type. Example Value m5.xlarge"
  required: true
- name: SECURITY_GROUP
  description: "Security Group Name"
  required: true
- name: IAM_PROFILE
  description: "IAM profile name"
  required: true
- name: PRIVATE_SUBNET
  description: "Private Subnet Name"
  required: true
