---
apiVersion: v1
kind: Template
objects:
- apiVersion: autoscaling.openshift.io/v1beta1
  kind: MachineAutoscaler
  metadata:
    name: ${ROLE}-${CLOUD_REGION_ZONE}
    namespace: openshift-machine-api
  spec:
    minReplicas: ${{MIN}}
    maxReplicas: ${{MAX}}
    scaleTargetRef:
      apiVersion: machine.openshift.io/v1beta1
      kind: MachineSet
      name: ${CLUSTER_ID}-${ROLE}-${CLOUD_REGION_ZONE}
parameters:
- name: CLUSTER_ID
  description: "Example Value - mycluster-dev-x85t8"
  required: true
- name: CLOUD_REGION_ZONE
  description: "Example Value - us-east-1a"
  required: true
- name: ROLE
  description: "Role of Machineset applying autoscaling to. Example Value - worker"
  required: true
- name: MIN
  description: "Min number of Machines per machineset"
  required: true
- name: MAX
  description: "Max number of Machines per machineset"
  required: true
